services:
  - type: web
    name: springboilerplate-app
    env: docker
    region: oregon  # or change to your preferred region
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: springboilerplate-db
          property: connectionString

databases:
  - name: springboilerplate-db
    plan: free
    region: oregon
    postgresMajorVersion: 15